apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: odoo
  namespace: ic-webapp 
  labels:
    app: odoo
    env: prod
data:
  ODOO_PASSWORD: dG90bw==
  POSTGRES_PASSWORD: dG90bw==
type: Opaque
