apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ic-webapp
  name: ic-webapp
  namespace: ic-webapp
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: ic-webapp

  template:
    metadata:
      labels:
        app: ic-webapp
    spec:
      containers:
      - image: lionie/ic-webapp:1.0
        name: ic-webapp
        env:
        - name: ODOO_URL
          value: http://localhost:30069/
        - name: PGADMIN_URL
          value: http://localhost:30050/
        ports:
        - containerPort: 8080
          name: ic-webapp
